### CREAR COMPRA
POST http://localhost:4000/api/compras
Content-Type: application/json

{
    "total": 12,
    "fecha": "2023-06-12",
    "proveedor_id": 3
}

### OBTENER TODAS LAS COMPRAS
GET http://localhost:4000/api/compras

### OBTENER COMPRA POR ID
GET http://localhost:4000/api/compras/3

### MODIFICAR COMPRA POR ID

PUT http://localhost:4000/api/compras/3
Content-Type: application/json

{
    "total": 20.50,
    "fecha": "2024-08-22",
    "proveedor_id": 1
}

### ELIMINAR COMPRA POR ID
DELETE http://localhost:4000/api/compras/1