### CREAR PROVEEDOR
POST http://localhost:4000/api/proveedores
Content-Type: application/json

{
    "nombre": "Proveedor random",
    "ruc": "00000134",
    "telefono": "100012234",
    "direccion": "av. Javier Prado"
}

### OBTENER TODOS LOS PROVEEDORES
GET http://localhost:4000/api/proveedores

### OBTENER PROVEEDOR POR ID
GET http://localhost:4000/api/proveedores/3

### MODIFICAR PROVEEDOR POR ID

PUT http://localhost:4000/api/proveedores/3
Content-Type: application/json

{
    "nombre": "Juan",
    "ruc": "003200134",
    "telefono": "1054634",
    "direccion": "av. San Luis"
}

### ELIMINAR PROVEEDOR POR ID
DELETE http://localhost:4000/api/proveedores/4