### CREAR ADMINISTRADOR
POST http://localhost:4000/api/administradores
Content-Type: application/json

{   
    "nombre": "Bryan Avalos",
    "usuario": "admin",
    "contrasenia": "admin"
}

### OBTENER ADMINISTRADOR POR ID
GET  http://localhost:4000/api/administradores/1

### ACTUALIZAR ADMINISTRADOR POR ID
PUT http://localhost:4000/api/administradores/actualizar/1
Content-Type: application/json

{
    "nombre": "Nuevo nombre de administradores",
    "usuario": "nuevo usuario",
    "contrasenia": "nueva contra",
    "dni": "75013015asd",
    "telefono": "915115894asd"
}

### CREAR VENDEDOR
POST http://localhost:4000/api/administradores/vendedores/crear
Content-Type: application/json

{
    "nombre": "Leonardo Jauregui",
    "usuario": "vendedor",
    "contrasenia": "vendedor",
    "dni": "75013015",
    "telefono": "915115894"
}

### ACTUALIZAR VENDEDOR POR ID
PUT http://localhost:4000/api/administradores/vendedores/actualizar/1
Content-Type: application/json

{
    "nombre": "Dimitri el rcsm",
    "usuario": "dimi",
    "contrasenia": "contrase",
    "dni": "75013015",
    "telefono": "915115894"
}

### MODIFICAR DATOS DEL ADMINISTRADOR POR ID
PUT http://localhost:4000/api/administradores/1
Content-Type: application/json

{
    "nombre": "Bryan Avalos Loa y Pardo Jesus administradores modificado",
    "usuario": "admin",
    "contrasenia": "contrasenia"
}
