### CREAR ADMINISTRADOR
POST http://localhost:4000/api/administradores
Content-Type: application/json

{
    "nombre": "Bryan",
    "usuario": "BR12",
    "contrasenia": "123456"
}

### ACTUALIZAR ADMINISTRADOR POR ID
PUT http://localhost:4000/api/administradores/actualizar/1
Content-Type: application/json

{
    "nombre": "Nuevo nombre de administrador",
    "usuario": "nuevo usuario",
    "contrasenia": "nueva contra",
    "dni": "75013015asd",
    "telefono": "915115894asd"
}

### CREAR VENDEDOR
POST http://localhost:4000/api/administradores/vendedores/crear
Content-Type: application/json

{
    "nombre": "Nombre del vendedor",
    "usuario": "usuario",
    "contrasenia": "contrasenia",
    "dni": "75013015",
    "telefono": "915115894"
}

### ACTUALIZAR VENDEDOR POR ID
PUT http://localhost:4000/api/administradores/vendedores/actualizar/1
Content-Type: application/json

{
    "nombre": "Dimitri el rcsm",
    "usuario": "dimi",
    "contrasenia": "contrase",
    "dni": "75013015",
    "telefono": "915115894"
}

### MODIFICAR DATOS DEL ADMINISTRADOR POR ID
PUT http://localhost:4000/api/administrador/1
Content-Type: application/json

{
    "nombre": "Bryan Avalos Loa y Pardo Jesus administrador modificado",
    "usuario": "admin",
    "contrasenia": "contrasenia"
}

### OBTENER TODOS LOS VENDEDORES
GET  http://localhost:4000/api/administrador/vendedores