### CREAR CATEGORIA
POST http://localhost:4000/api/categorias
Content-Type: application/json

{
    "nombre": "categoria 1"
}

### OBTENER TODOS LAS CATEGORIAS
GET http://localhost:4000/api/categorias

### OBTENER CATEGORIA POR ID
GET http://localhost:4000/api/categorias/1

### MODIFICAR CATEGORIA POR ID

PUT http://localhost:4000/api/categorias/1
Content-Type: application/json

{
    "nombre": "categoria 1 modificada"
}

### ELIMINAR CATEGORIA POR ID
DELETE http://localhost:4000/api/categorias/1