### CREAR CLIENTE
POST http://localhost:4000/api/clientes
Content-Type: application/json

{
    "nombre": "Juan Perez",
    "telefono": "987654321",
    "ruc": "12345678901"
}

### OBTENER TODOS LOS CLIENTES
GET http://localhost:4000/api/clientes

### OBTENER CLIENTE POR ID
GET http://localhost:4000/api/clientes/3

### MODIFICAR CLIENTE POR ID
PUT http://localhost:4000/api/clientes/3
Content-Type: application/json

{
    "nombre": "Ana Lopez",
    "telefono": "987654321",
    "ruc": "10987654321"
}

### ELIMINAR CLIENTE POR ID
DELETE http://localhost:4000/api/clientes/3
