### CREAR DETALLE DE VENTA
POST http://localhost:4000/api/detalleventas
Content-Type: application/json

{
    "cantidad": 12 ,
    "monto": 50.5,
    "ventaId": 3,
    "productoId": 1
}

### OBTENER TODOS LOS DETALLES DE VENTAS

GET http://localhost:4000/api/detalleventas

### OBTENER DETALLE DE VENTA POR ID
GET http://localhost:4000/api/detalleventas/1

### MODIFICAR DETALLE DE VENTA POR ID

PUT http://localhost:4000/api/detalleventas/1
Content-Type: application/json

{
    "cantidad": 24 ,
    "monto": 100.55,
    "ventaId": 3,
    "productoId": 1
}
