### CREAR DETALLE DE VENTA
POST http://localhost:4000/api/detallecompras
Content-Type: application/json

{
    "cantidad": 12 ,
    "monto": 50.5,
    "compraId": 1,
    "productoId": 1
}

### OBTENER TODOS LOS DETALLES DE VENTAS

GET http://localhost:4000/api/detallecompras

### OBTENER DETALLE DE VENTA POR ID
GET http://localhost:4000/api/detallecompras/1

### MODIFICAR DETALLE DE VENTA POR ID

PUT http://localhost:4000/api/detallecompras/1
Content-Type: application/json

{
    "cantidad": 24 ,
    "monto": 100.55,
    "compraId": 1,
    "productoId": 1
}