### CREAR IMAGEN

POST http://localhost:4000/api/imagenproducto/
Content-Type: application/json

{
    "url": "Imagen X",
    "publicidad": "Imagen X"
}



###OBTENER TODOS LAS IMAGENES
GET http://localhost:4000/api/imagenproducto/


###OBTENER IMAGEN 1
GET http://localhost:4000/api/imagenproducto/1/


###ACTUALIZAR IMAGEN 1
PUT http://localhost:4000/api/imagenproducto/1
Content-Type: application/json

{
    "url": "imagen 1 modificada",
    "publicidad": "imagen 1 modificada"
}

###ELIMINAR IMAGEN 2
DELETE http://localhost:4000/api/imagenproducto/1
