###OBTENER PRODUCTOS
GET http://localhost:4000/api/productos

###CREAR PRIMERO MARCA
POST http://localhost:4000/api/marcas/
Content-Type: application/json

{
    "nombre": "marca X"
}

###CREAR PRIMERO CATEGORIA
POST http://localhost:4000/api/categorias/
Content-Type: application/json

{
    "nombre": "categoria X"
}

###CREAR PRIMERO IMAGEN
POST http://localhost:4000/api/imagenproducto/
Content-Type: application/json

{
    "url": "Imagen X",
    "publicidad": "Imagen X"
}


###CREAR PRODUCTO
POST http://localhost:4000/api/producto/
Content-Type: application/json

{
  "nombre": "Pan",
  "precioCosto": "0.50",
  "precioVenta": "20",
  "stock": "50",
  "categoriaId": "1",
  "marcaId": "1",
  "imagenProductoId": "1"
}

###OBTENER PRODUCTO 1
GET http://localhost:4000/api/producto/1/


###ACTUALIZAR PRODUCTO 1
PUT http://localhost:4000/api/producto/1/
Content-Type: application/json

{
  "nombre": "Pan Pizza",
  "precioCosto": "0.50",
  "precioVenta": "20000",
  "stock": "50",
  "categoriaId": "1",
  "marcaId": "1",
  "imagenProductoId": "1"
}

###ELIMINAR PRODUCTO 2
DELETE http://localhost:4000/api/producto/2/

