### CREAR COMPRA
POST http://localhost:4000/api/proveedores
Content-Type: application/json

{
    "nombre": "Alicorp",
    "ruc": "123456733",
    "telefono": "4335677",
    "direccion": "Calle 13 MZ A"
}

### OBTENER TODAS LAS COMPRAS
GET http://localhost:4000/api/proveedores

### OBTENER COMPRA POR ID
GET http://localhost:4000/api/proveedores/2

### MODIFICAR COMPRA POR ID

PUT http://localhost:4000/api/proveedores/1
Content-Type: application/json

{
    "nombre": "PYG",
    "ruc": "123456733",
    "telefono": "514335677",
    "direccion": "Calle 13 MZ A"
}

### ELIMINAR COMPRA POR ID
DELETE http://localhost:4000/api/proveedores/1