### CREAR ROL
POST http://localhost:4000/api/roles
Content-Type: application/json

{
    "nombre": "vendedor"
}

### OBTENER TODOS LOS ROLES
GET http://localhost:4000/api/roles

### OBTENER ROL POR ID
GET http://localhost:4000/api/roles/1

### MODIFICAR ROL POR ID

PUT http://localhost:4000/api/roles/1
Content-Type: application/json

{
    "nombre": "Admin"
}

### ELIMINAR ROL POR ID
DELETE http://localhost:4000/api/roles/2