### CREAR USUARIO
POST http://localhost:4000/api/usuarios
Content-Type: application/json

{
    "nombre": "Bryan Avalos Loa y Pardo Jesus",
    "usuario": "qwerson",
    "contrasenia": "dakota",
    "rolId": 1
}

### OBTENER TODOS LOS USUARIOS
GET http://localhost:4000/api/usuarios

### OBTENER USUARIO POR ID
GET http://localhost:4000/api/usuarios/1

### MODIFICAR USUARIO POR ID

PUT http://localhost:4000/api/usuarios/1
Content-Type: application/json

{
    "nombre": "Mauricio Ramirez Milla",
    "usuario": "mauriXtreme",
    "contrasenia": "george",
    "rolId": 1
}

### ELIMINAR USUARIO POR ID
DELETE http://localhost:4000/api/usuarios/2

### INICIAR SESION
POST  http://localhost:4000/api/usuarios/autenticacion/iniciarSesion
Content-Type: application/json

{
    "usuario": "usuario",
    "contrasenia": "contrasenia"
}