### OBTENER TODOS LOS VENDEDORES
GET http://localhost:4000/api/vendedores

### OBTENER VENDEDOR POR USUARIO ID
GET http://localhost:4000/api/vendedores/usuario/2

### OBTENER VENDEDOR POR DNI
GET http://localhost:4000/api/vendedores/dni/75013015

### CREAR VENDEDOR
POST http://localhost:4000/api/vendedores
Content-Type: application/json

{
    "nombre": "Leonardo Jauregui",
    "usuario": "vendedor",
    "contrasenia": "vendedor",
    "dni": "75013015",
    "telefono": "915115894"
}
