### CREAR VENTA
POST http://localhost:4000/api/ventas
Content-Type: application/json

{
    "fecha": "2023-06-12",
    "subtotal": 100.00,
    "igv": 18.00,
    "total": 118.00,
    "vendedorId": 3,
    "clienteId": 1,
    "detalles": [
        {
            "cantidad": 2,
            "monto": 50.00,
            "productoId": 1
        },
        {
            "cantidad": 1,
            "monto": 68.00,
            "productoId": 2
        }
    ]
}

### OBTENER TODAS LAS VENTAS
GET http://localhost:4000/api/ventas

### OBTENER VENTA POR ID
GET http://localhost:4000/api/ventas/3

### MODIFICAR VENTA POR ID
PUT http://localhost:4000/api/ventas/3
Content-Type: application/json

{
    "fecha": "2024-08-22",
    "subtotal": 150.00,
    "igv": 27.00,
    "total": 177.00,
    "vendedorId": 2,
    "clienteId": 3
}

### ELIMINAR VENTA POR ID
DELETE http://localhost:4000/api/ventas/1
